[package]
name = "module_5_rust_app"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.1", features = ["macros"] }
serde = { version = "1.0.218", features = ["derive"] }
tokio = { version = "1", features = ["full"] }